services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: "mariadb"
    ports: 
      -  "3306:3306"
    env_file: ".env"
    volumes:
      - type: bind
        source: /Users/voszadcs/Documents/data
        target: /var/lib/mysql

volumes:
  wp_db: