services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: "mariadb"
    ports: 
      -  "3306:3306"
    env_file: ".env"
    volumes:
     - wp_db:/var/lib/mysql

volumes:
  wp_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/voszadcs/Documents/data